# Generated by Django 4.1.7 on 2023-02-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval_add',
            name='text',
            field=models.TextField(blank=True, max_length=2750, verbose_name='Описание путишествия'),
        ),
    ]
