# Generated by Django 4.1.7 on 2023-02-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_alter_pereval_add_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval_add',
            name='text',
            field=models.TextField(max_length=2750, verbose_name='Описание путишествия'),
        ),
    ]
