# Generated by Django 4.1.7 on 2023-02-24 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_alter_pereval_add_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pereval_add',
            options={'verbose_name': 'Информация о маршруте', 'verbose_name_plural': 'Информация о маршруте'},
        ),
        migrations.AlterModelOptions(
            name='pereval_images',
            options={'verbose_name': 'Фотографии', 'verbose_name_plural': 'Фотографии'},
        ),
    ]
